# Generated by Django 3.0.6 on 2020-05-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_host_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
